# Site settings
title: Jirawat Boonkumnerd
# generate from https://www.svgbackgrounds.com/
header-img: data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='200' height='200' viewBox='0 0 800 800'%3E%3Cg fill='none' stroke='%23404' stroke-width='1'%3E%3Cpath d='M769 229L1037 260.9M927 880L731 737 520 660 309 538 40 599 295 764 126.5 879.5 40 599-197 493 102 382-31 229 126.5 79.5-69-63'/%3E%3Cpath d='M-31 229L237 261 390 382 603 493 308.5 537.5 101.5 381.5M370 905L295 764'/%3E%3Cpath d='M520 660L578 842 731 737 840 599 603 493 520 660 295 764 309 538 390 382 539 269 769 229 577.5 41.5 370 105 295 -36 126.5 79.5 237 261 102 382 40 599 -69 737 127 880'/%3E%3Cpath d='M520-140L578.5 42.5 731-63M603 493L539 269 237 261 370 105M902 382L539 269M390 382L102 382'/%3E%3Cpath d='M-222 42L126.5 79.5 370 105 539 269 577.5 41.5 927 80 769 229 902 382 603 493 731 737M295-36L577.5 41.5M578 842L295 764M40-201L127 80M102 382L-261 269'/%3E%3C/g%3E%3Cg fill='%23505'%3E%3Ccircle cx='769' cy='229' r='6'/%3E%3Ccircle cx='539' cy='269' r='6'/%3E%3Ccircle cx='603' cy='493' r='6'/%3E%3Ccircle cx='731' cy='737' r='6'/%3E%3Ccircle cx='520' cy='660' r='6'/%3E%3Ccircle cx='309' cy='538' r='6'/%3E%3Ccircle cx='295' cy='764' r='6'/%3E%3Ccircle cx='40' cy='599' r='6'/%3E%3Ccircle cx='102' cy='382' r='6'/%3E%3Ccircle cx='127' cy='80' r='6'/%3E%3Ccircle cx='370' cy='105' r='6'/%3E%3Ccircle cx='578' cy='42' r='6'/%3E%3Ccircle cx='237' cy='261' r='6'/%3E%3Ccircle cx='390' cy='382' r='6'/%3E%3C/g%3E%3C/svg%3E
email: jo06942@gmail.com
description: "A Software Engineer"
keyword: "Full-Stack Developer, Programming, Machine Learning, IoT"
url: "https://ntsd.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Build settings
permalink: /:title/
paginate: 10
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]
anchorjs: true # if you want to customize anchor. check out line:181 of `post.html`
future: true # Publish posts or collection documents with a future date.

# SNS settings
RSS: false
github_username: ntsd
# twitter_username: ntsd_me
facebook_username: jo.ntsd
linkedin_username: ntsd
# github_btn: ntsd.github.io # Github repository name

# Config compress html
# documents: https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Seo Tag setting
# document: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# document advance: https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md
defaults:
  - scope:
      path: ""
    values:
      image: /pwa/icons/512.png
logo: /pwa/icons/512.png
twitter:
  username: ntsd_me
  card: summary
facebook: 
  app_id: 523337598616322
  publisher: ntsd.me
  admins: jo.ntsd
social:
  name: Jirawat Boonkumnerd
  links:
    - https://web.facebook.com/ntsd.me
    - https://github.com/ntsd
    - https://www.linkedin.com/in/ntsd

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important

# Facebook comments setting
facebook_app_id: 523337598616322
facebook_comments: false

# Disqus settings
# disqus_username: "ntsd-github-io"

# Google Analytics
# ga_track_id: 'UA-166826202-1' # Format: UA-xxxxxx-xx
# ga_domain: ntsd.me

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "<h4>Jirawat Boonkumnerd</h4> A Software Engineer"
sidebar-avatar: /img/me.jpg # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Quotes quotes will show when description or subtitle is null
show_quotes: false
quotes: [
    "“Choose a job that you love and you will never have to work a day in your life” – Confucius",
    "“I have not failed. I’ve just found 10,000 ways that won’t work.” – Thomas Edison",
    "“Never before in history has innovation offered promise of so much to so many in so short a time.” – Bill Gates",
    "“The science of today is the technology of tomorrow.” – Edward Teller",
    "‘I learned that focus is key, not just in running a company, but in your personal life as well.’ - Tim Cook",
    "“Wear your failure as a badge of honor.” - Sundar Pichai",
    "“Find that thing you are super passionate about.” - Mark Zuckerberg",
    "“You build your own strategy. You don’t define it by what another competitor is doing.” - Ginni Rometty",
    "“If you're passionate about something and you work hard, then I think you will be successful.” - Pierre Omidyar",
    "“Diligence is the mother of good luck.” - Benjamin Franklin",
    "“Whether you think you can, or think you can't you're right.” - Henry Ford",
    "“The value of an idea lies in the using of it.” - Thomas Edison",
    "“Make every detail perfect and limit the number of details to perfect.” - Jack Dorsey",
    "“Don't worry about failure; you only have to be right once.” - Drew Houston",
    "“Any time is a good time to start a company.” - Ron Conway",
    "“Nothing works better than just improving your product.” - Joel Spolsky",
    "“Your most unhappy customers are your greatest source of learning.” - Bill Gates",
    "“Life is too short to hang out with people who aren’t resourceful.” - Jeff Bezos"
]
