# Site settings
title: NTSD Blog
SEOTitle: NTSD Blog | Jirawat Boonkumnerd
header-img: img/post-bg-os-metro.jpg
email: jo06942@gmail.com
description: "A Software Engineer \n who interesting in Machine Learning"
keyword: "ntsd, Software Engineer, Machine Learning, Bot, Programming, Python, JavaScript, Java"
url: "https://ntsd.me" # your host, for absolute URL
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
github_username:    ntsd
# twitter_username:
facebook_username:  jo.ntsd
linkedin_username:  jirawat-boonkumnerd-815832114

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM # use Github Flavored Markdown !important

# Disqus settings
disqus_username: "ntsd-github-io"

# Netease settings
netease_comment: false

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-29710747-1' # Format: UA-xxxxxx-xx
ga_domain: ntsd.github.io

# Sidebar settings
sidebar: true # whether or not using Sidebar.
sidebar-about-description: "A Software Engineer \n who interesting in Machine Learning"
sidebar-avatar: https://avatars0.githubusercontent.com/u/8283616?s=460&v=4 # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true # whether or not using Feature-Tags
featured-condition-size: 0 # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Quotes quotes will show when description or subtitle is null
quotes: [
    "“Choose a job that you love and you will never have to work a day in your life” – Confucius",
    "“I have not failed. I’ve just found 10,000 ways that won’t work.” – Thomas Edison",
    "“Never before in history has innovation offered promise of so much to so many in so short a time.” – Bill Gates",
    "“The science of today is the technology of tomorrow.” – Edward Teller",
    "‘I learned that focus is key, not just in running a company, but in your personal life as well.’ - Tim Cook",
    "“Wear your failure as a badge of honor.” - Sundar Pichai",
    "“Find that thing you are super passionate about.” - Mark Zuckerberg",
    "“You build your own strategy. You don’t define it by what another competitor is doing.” - Ginni Rometty",
    "“If you're passionate about something and you work hard, then I think you will be successful.” - Pierre Omidyar",
    "“Diligence is the mother of good luck.” - Benjamin Franklin",
    "“Whether you think you can, or think you can't you're right.” - Henry Ford",
    "“The value of an idea lies in the using of it.” - Thomas Edison",
    "“Make every detail perfect and limit the number of details to perfect.” - Jack Dorsey",
    "“Don't worry about failure; you only have to be right once.” - Drew Houston",
    "“Any time is a good time to start a company.” - Ron Conway",
    "“Nothing works better than just improving your product.” - Joel Spolsky",
    "“Your most unhappy customers are your greatest source of learning.” - Bill Gates",
    "“Life is too short to hang out with people who aren’t resourceful.” - Jeff Bezos"
]
